#!/bin/bash
clear
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mWAIT \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mWAIT \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "INSTALLING SLOWDNS SSL" ; tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e ""
echo -e "      This script will install the"
echo -e "     slowdns for DNS tunneling with SSL."
echo -e ""
echo -e "         \033[1;33mInstaller made by @Laael and Modded/Translated by @KhaledAGN ❤️ \033[1;37m"
echo -e ""
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "UPDATING PACKAGE LIST..."
fun_att () {
apt update && apt upgrade -y
}
fun_bar 'fun_att'
echo -e "INSTALLING AND UPDATING REQUIRED PACKAGES..."
install_pkgs () {
apt install screen -y
apt install cron -y
apt install iptables -y
service cron reload
service cron restart
service iptables reload
service iptables restart
}
fun_bar 'install_pkgs'
echo ""
echo -e "CONFIGURING IPTABLES..."
ipt_set () {
cd /etc
rm -rf rc.local
wget https://github.com/khaledagn/DNS-AGN/raw/main/rc.local
chmod +x /etc/rc.local
systemctl enable rc-local
systemctl start rc-local
}
fun_bar 'ipt_set'
clear
echo ""
echo -e "\033[1;31m ATTENTION IN THIS STAGE! \033[1;33m"
echo ""
cd /etc/slowdns
echo -ne "\033[1;32m ENTER YOUR NS (NAMESERVER)\033[1;37m: "; read nameserver
touch infons
echo $nameserver > infons
set_ns () {
sleep 1
wget https://raw.githubusercontent.com/khaledagn/DNS-AGN/main/ssl/startdns 
wget https://raw.githubusercontent.com/khaledagn/DNS-AGN/main/ssl/restartdns
chmod +x startdns
chmod +x restartdns
sed -i "s;1234;$nameserver;g" /etc/slowdns/startdns > /dev/null 2>&1
sed -i "s;1234;$nameserver;g" /etc/slowdns/restartdns > /dev/null 2>&1
cp startdns /bin/
cp restartdns /bin/
}
fun_bar 'set_ns'
echo ""
echo "Checking for existence of key"
sleep 2
echo ""
echo "       Please wait...   "
sleep 2
cd
key1="/root/server.key"
key2="/root/server.pub"
if [ -f $key1 ] && [ -f $key2 ]
then
echo -e "Key file found!"
sleep 1
echo ""
key () {
echo "How do you want to get your key?"
echo ""
echo "[ 1 ] | Use existing key in file"
echo "[ 2 ] | Delete file and generate new key"
echo "[ 3 ] | Delete file and use default key"
echo "[ x ] | Abort installation"
echo ""
echo -ne "Enter an option: " && read option
case $option in
1) Option1 ;;
2) Option2 ;;
3) Option3 ;;
x) OptionX ;;
*) "Unknown command" ; echo ; key;;
esac
}
Option1 () {
echo -ne "Restoring existing key..." && sleep 2 && echo "OK!"
echo ""
echo -e "FINISHING..."
finish_ist () {
cd
cp server.key /etc/slowdns/ && cp server.pub /etc/slowdns/
cd /etc/slowdns
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALLATION COMPLETED!\033[0m"
echo ""
echo -ne "\033[1;33mYOUR NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mYOUR PUBLIC KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mTERMUX COMMAND:\033[0m curl -sO https://github.com/khaledagn/DNS-AGN/raw/main/files/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m [1;33m YOUR KEY is saved in the file /root/server.pub\033[0m"
echo -e "\033[1;33mKeep it in a safe place, you may need it in the future!\033[0m"
echo ""
read -p "Press [Enter] to return to the menu or CTRL+C to exit"
}
Option2 () {
cd
rm server.key server.pub
echo "Generating new key"
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
echo -e "FINISHING..."
finish_ist () {
cd
cp server.key /etc/slowdns/ && cp server.pub /etc/slowdns/
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
cd /etc/slowdns && ./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALLATION COMPLETED!\033[0m"
echo ""
echo -ne "\033[1;33mYOUR NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mYOUR PUBLIC KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mTERMUX COMMAND:\033[0m curl -sO https://github.com/khaledagn/DNS-AGN/raw/main/files/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m [1;33m YOUR KEY is saved in the file /root/server.pub\033[0m"
echo -e "\033[1;33mKeep it in a safe place, you may need it in the future!\033[0m"
echo ""
read -p "Press [Enter] to return to the menu or CTRL+C to exit"
slowdns
}
Option3 () {
echo -e "Downloading default key pair..."
cd
rm server.key server.pub
wget https://raw.githubusercontent.com/khaledagn/DNS-AGN/main/server.key
wget https://raw.githubusercontent.com/khaledagn/DNS-AGN/main/server.pub
cp server.key /etc/slowdns/ && cp server.pub /etc/slowdns/
sleep 1
echo -e "Download Completed"
sleep 1
cd /etc/slowdns/
echo -e "FINISHING..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALLATION COMPLETED!\033[0m"
echo ""
echo -ne "\033[1;33mYOUR NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mYOUR PUBLIC KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mTERMUX COMMAND:\033[0m curl -sO https://github.com/khaledagn/DNS-AGN/raw/main/files/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m [1;33m YOUR KEY is saved in the file /root/server.pub\033[0m"
echo -e "\033[1;33mKeep it in a safe place, you may need it in the future!\033[0m"
echo ""
read -p "Press [Enter] to return to the menu or CTRL+C to exit"
slowdns
}
OptionX () {
exit
}
key
else
echo -e "There is no key in the logs"
echo ""
key_gen () {
echo "How do you want to get your key?"
echo ""
echo "[ 1 ] | Generate on installation"
echo "[ 2 ] | Use the default key"
echo "[ x ] | Abort installation"
echo ""
echo -ne "Enter an option: " && read opc_key
case $opc_key in
1) opc_key1 ;;
2) opc_key2 ;;
x) opc_keyx ;;
*) "Unknown command" ; echo ; key_gen;;
esac
}
opc_key1 () {
echo "Generating your key..."
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
echo -e "FINISHING..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALLATION COMPLETED!\033[0m"
echo ""
echo -ne "\033[1;33mYOUR NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mYOUR PUBLIC KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mTERMUX COMMAND:\033[0m curl -sO https://github.com/khaledagn/DNS-AGN/raw/main/files/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m [1;33m YOUR KEY is saved in the file /root/server.pub\033[0m"
echo -e "\033[1;33mKeep it in a safe place, you may need it in the future!\033[0m"
echo ""
read -p "Press [Enter] to return to the menu or CTRL+C to exit"
slowdns
}
opc_key2 () {
echo -e "Downloading default key pair..."
cd
wget https://raw.githubusercontent.com/khaledagn/DNS-AGN/main/server.key
wget https://raw.githubusercontent.com/khaledagn/DNS-AGN/main/server.pub
sleep 1
echo -e "Download Completed"
sleep 1
cd /etc/slowdns/
echo -e "FINISHING..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALLATION COMPLETED!\033[0m"
echo ""
echo -ne "\033[1;33mYOUR NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mYOUR PUBLIC KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mTERMUX COMMAND:\033[0m curl -sO https://github.com/khaledagn/DNS-AGN/raw/main/files/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m [1;33m YOUR KEY is saved in the file /root/server.pub\033[0m"
echo -e "\033[1;33mKeep it in a safe place, you may need it in the future!\033[0m"
echo ""
read -p "Press [Enter] to return to the menu or CTRL+C to exit"
}
opc_keyx () {
echo "Aborting installation"
sleep 2
exit
}
key_gen
fi
